#!/bin/sh
#-
# mkimage.sh — turn a stock OPNsense live image into an unattended
# installer image.
#
# Takes a stock OPNsense "vga" .img (or .iso), injects the
# autoinstall.sh headless installer + an optional config.xml + a boot
# trigger, and writes out a customized image. Boot that image in a VM
# (or write it to a USB stick) and it installs OPNsense to disk with no
# interaction, then reboots into the installed, configured system.
#
# *** MUST RUN ON FreeBSD *** — it mounts the image's UFS filesystem
# read-write via mdconfig(8), which macOS and Linux cannot do reliably.
# Use the box you're installing onto's hypervisor host if it's FreeBSD,
# a throwaway FreeBSD VM, or an existing OPNsense/FreeBSD machine.
#
# MIT licensed. See LICENSE.

set -eu

SELF_DIR=$(cd "$(dirname "$0")" && pwd)

usage() {
	cat >&2 <<EOF
Usage: $0 -i INPUT.img -o OUTPUT.img [options]

  -i INPUT     stock OPNsense vga image; .img, or compressed
               .img.bz2 / .img.xz / .img.gz (decompressed in place)
  -o OUTPUT    path to write the customized image
  -c CONFIG    config.xml to install as the target's /conf/config.xml
               (optional; omit to leave OPNsense's default config)
  -d DISK      target install disk inside the VM (default: auto)
  -s SWAP      swap partition size, gpart syntax e.g. 8G (default: none)
  -f FINAL     reboot | halt  when the install finishes (default: reboot)
  -a SCRIPT    path to autoinstall.sh (default: alongside this script)

Must run on FreeBSD (uses mdconfig + UFS r/w mount).
EOF
	exit 1
}

INPUT= OUTPUT= CONFIG= DISK=auto SWAP= FINAL=reboot
AUTOINSTALL="${SELF_DIR}/autoinstall.sh"

while getopts "i:o:c:d:s:f:a:h" opt; do
	case "${opt}" in
	i) INPUT=${OPTARG} ;;
	o) OUTPUT=${OPTARG} ;;
	c) CONFIG=${OPTARG} ;;
	d) DISK=${OPTARG} ;;
	s) SWAP=${OPTARG} ;;
	f) FINAL=${OPTARG} ;;
	a) AUTOINSTALL=${OPTARG} ;;
	*) usage ;;
	esac
done

[ -n "${INPUT}" ] && [ -n "${OUTPUT}" ] || usage
[ "$(uname -s)" = "FreeBSD" ] || { echo "ERROR: must run on FreeBSD." >&2; exit 1; }
[ "$(id -u)" = "0" ] || { echo "ERROR: must run as root (mdconfig/mount)." >&2; exit 1; }
[ -r "${INPUT}" ] || { echo "ERROR: input image ${INPUT} not readable." >&2; exit 1; }
[ -r "${AUTOINSTALL}" ] || { echo "ERROR: autoinstall.sh not found at ${AUTOINSTALL}." >&2; exit 1; }
[ -z "${CONFIG}" ] || [ -r "${CONFIG}" ] || { echo "ERROR: config ${CONFIG} not readable." >&2; exit 1; }

# Materialize the working image at OUTPUT, decompressing if needed.
# Accepting the compressed image directly matters for the Vagrant
# wrapper: it ferries the small .bz2 into the VM (~5x less data over
# the slow link) and decompresses here, rather than shipping the full
# decompressed image across.
case "${INPUT}" in
*.bz2)
	command -v bunzip2 >/dev/null 2>&1 || { echo "ERROR: bunzip2 not found." >&2; exit 1; }
	echo ">> decompressing (bzip2) ${INPUT} -> ${OUTPUT}"
	bunzip2 -c "${INPUT}" > "${OUTPUT}"
	;;
*.xz)
	command -v xz >/dev/null 2>&1 || { echo "ERROR: xz not found." >&2; exit 1; }
	echo ">> decompressing (xz) ${INPUT} -> ${OUTPUT}"
	xz -dc "${INPUT}" > "${OUTPUT}"
	;;
*.gz)
	echo ">> decompressing (gzip) ${INPUT} -> ${OUTPUT}"
	gunzip -c "${INPUT}" > "${OUTPUT}"
	;;
*)
	echo ">> copying ${INPUT} -> ${OUTPUT}"
	cp "${INPUT}" "${OUTPUT}"
	;;
esac

MD=$(mdconfig -a -t vnode -f "${OUTPUT}")
echo ">> attached as /dev/${MD}"

MNT=$(mktemp -d /tmp/opnsense-autoinstall.XXXXXX)

cleanup() {
	umount "${MNT}" 2>/dev/null || true
	mdconfig -d -u "${MD}" 2>/dev/null || true
	rmdir "${MNT}" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# Find the freebsd-ufs partition on the image and mount it r/w.
UFS_PART=$(gpart show "${MD}" | awk '$4 == "freebsd-ufs" { print $3; exit }')
[ -n "${UFS_PART}" ] || { echo "ERROR: no freebsd-ufs partition found on image." >&2; exit 1; }
echo ">> mounting /dev/${MD}p${UFS_PART} (the live root) read-write"
mount -t ufs -o rw "/dev/${MD}p${UFS_PART}" "${MNT}"

echo ">> injecting autoinstall.sh + config + boot trigger"
install -m 0755 "${AUTOINSTALL}" "${MNT}/usr/local/sbin/opnsense-autoinstall"

# Per-build configuration consumed by the autoinstall script.
cat > "${MNT}/etc/opnsense-autoinstall.conf" <<EOF
# Generated by mkimage.sh
TARGET_DISK="${DISK}"
SWAP_SIZE="${SWAP}"
FINAL="${FINAL}"
CONFIG_XML="/etc/opnsense-autoinstall-config.xml"
EOF

if [ -n "${CONFIG}" ]; then
	install -m 0600 "${CONFIG}" "${MNT}/etc/opnsense-autoinstall-config.xml"
else
	# No config supplied; tell the installer not to inject one.
	sed -i '' 's|^CONFIG_XML=.*|CONFIG_XML=""|' "${MNT}/etc/opnsense-autoinstall.conf"
fi

# Boot trigger: run the headless installer late in multi-user startup.
# /etc/rc.local is the simplest hook; if a given OPNsense release does
# not honor it on the live image, the alternative is to repoint the
# console autologin at opnsense-autoinstall (see README "Boot trigger").
cat > "${MNT}/etc/rc.local" <<'EOF'
#!/bin/sh
# Installed by opnsense-autoinstall/mkimage.sh — run the headless
# installer once, on the live system, then reboot/halt.
if [ -x /usr/local/sbin/opnsense-autoinstall ]; then
	/usr/local/sbin/opnsense-autoinstall
fi
EOF
chmod 0755 "${MNT}/etc/rc.local"

sync
echo ">> done. Customized unattended image: ${OUTPUT}"
echo "   Boot it in the target VM (or write to USB) to install hands-off."
